version: '3.8'
services:
    core-web:
        container_name: core-web
        build:
            context: ./core-web
            dockerfile: Dockerfile
            target: dev
        image: shawnstewart/kkt:dev
        restart: always
        environment:
            - NODE_ENV=development
            - FORCE_COLOR=true
        ports:
            - 8001:8001
    react-chat:
        container_name: react-chat
        build:
            context: ./react-chat
            dockerfile: Dockerfile
            target: dev
        image: shawnstewart/react-chat:dev
        restart: always
        environment:
            - NODE_ENV=development
