services:
    core-web:
        build:
            target: release
        image: shawnstewart/kkt:latest
        environment:
            - NODE_ENV=production
    react-chat:
        build:
            target: release
        image: shawnstewart/react-chat:latest
        environment:
            - NODE_ENV=production
        ports:
            - 3000:80

