version: '3.8'
services:
    core-web:
        volumes:
            - ./core-web:/app
            - core-web_node-modules:/app/node_modules
    react-chat:
        ports:
            - 3000:3000
        volumes:
            - ./react-chat:/app
            - react-chat_node-modules:/app/node_modules
volumes:
    core-web_node-modules:
    react-chat_node-modules:
